name: GitHub CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20 # Escolha a versão do Node.js adequada ao seu projeto

      - name: Install Dependencies
        run: npm install

      - name: Run Jest Tests
        run: npm run test:ci # Ou o comando que você usa para executar seus testes com Jest
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout main # Certifique-se de estar na branch 'main'
          git pull # Atualize o repositório
          git branch -D gh-pages # Exclua a branch 'gh-pages' se ela já existir
          git checkout --orphan gh-pages
          git reset --hard
          mv out/* . # Mova os arquivos da pasta 'out' para a raiz do projeto
          git add -A
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}