name: GitHub CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20 # Escolha a versão do Node.js adequada ao seu projeto

      - name: Install Dependencies
        run: npm install

      - name: Run Jest Tests
        run: npm test # Ou o comando que você usa para executar seus testes com Jest
